name: Test build (s9pk artifact)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build test package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/blisspoint-v0.6.0.tar
          tags: blisspoint:v0.6.0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blisspoint-v0.6.0-test-package
          path: /tmp/blisspoint-v0.6.0.tar
